version: '3.8'

services:
  dbsm:
    image: mysql:8.0
    container_name: mysql_sm
    restart: always
    env_file:
      - ../.env
    ports:
      - "3309:3306"
    volumes:
      - mysql_datasm:/var/lib/mysql

volumes:
  mysql_datasm: